import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Figtree } from "next/font/google";

const figtree = Figtree({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-figtree",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${figtree.variable} font-sans font-light`}>
      <body>{children}</body>
    </html>
  );
}
